### ISSUE TITLE
How can I add a custom CSS to the build presentation?

### ISSUE THREAD

**Issue by DavidBruant** [lmtm/prez#13]
I've been doing ugly things all over the place. It works as I need it to, but I'm not satisfied
- https://github.com/anthill/training/pull/9/files#diff-4ff8d55fecfb85b86d663817a6a7a340R5
- https://github.com/anthill/training/pull/9/files#diff-9c01ad1efa2b804fd1575fe59e3a68e0R5

Is there a way to provide a custom CSS file to the final built presentation?

**Comment by Delapouite** [comment]
Yes.

You need to add the path to your custom CSS file into `includes.txt` : 
https://github.com/byteclubfr/prez/blob/master/data/init/includes.txt

Also, if you want to apply CSS styles to a specific chapter (vertical stack of slides), I've just added in 4.6 a `chapter-*` `id` to `<section>` elements.

For instance, if some slides are grouped into the `slides/foo` dir, like `slides/foo/bar.md`, `slides/foo/qux.md` then the following HTML is now generated : 

``` html
<section class="chapter" id="chapter-foo">
  <section class="slide" id="bar">…</slide>
  <section class="slide" id="qux">…</slide>
  …
</section>
```
