### ISSUE TITLE
Code Syntax Highlighting does not work consistently

### ISSUE THREAD

**Issue by dola** [lmtm/prez#27]
Hi there
I was trying to use the syntax highlighting and it seems to only work for some of my code blocks. If I manually uncomment the plugin definition of reveal.js in the index, it seems to work correctly.

Is it possible that this should not be commented out?
See:
https://github.com/byteclubfr/prez/blob/master/data/index.html#L60

**Comment by Delapouite** [comment]
Hi.
Do you provide hints of what language is about to be highlighted at the beginning of each fence block? In some situation highlight.js is not smart enough to guess the righ language.

prez currently provides : `"highlight.js": "^9.1.0",` which resolves to 9.8.0 the last version released.

**Comment by dola** [comment]
I do yes. It seems to be weird that the first bigger multiline code block works correctly and all subsequent ones do not get highlighted anymore.
I think it might be a problem with the underlying highlighting implementation in the default marked parser.

**Comment by dola** [comment]
Sorry for the inconvenience. It was my fault, the code blocks that did not highlight had syntax errors. Therefor my problem solved itself ;)
