### ISSUE TITLE
Math rendering

### ISSUE THREAD

**Issue by JoyMonteiro** [lmtm/prez#6]
Hello,

would it be possible to make math rendering available by default. I set it up
on my system using https://github.com/j13z/reveal.js-math-katex-plugin, and it works
without requiring MathJax (and therefore, an internet connection)

**Comment by szaghi** [comment]
The use of katex is interesting, thank you for sharing. Indeed, it is also possible to setup mathjax for offline rendering: I use this setup in https://github.com/szaghi/MaTiSSe. I will try to use your katex setup, thank you.

I also thank fir prez, it is very nice and it provides a lot of inspiration.

My best regards.

**Comment by drewsday** [comment]
I added a line to the file /usr/local/lib/node_modules/prez/data/index.html to include the MathJax plugin every time prez is run.  After the last reveal.js dependency I added: 

```
    { src: 'plugin/math/math.js', async: true }
```

...which makes my life a whole lot easier.

**Comment by JoyMonteiro** [comment]
@drewsday I did do that, but it just might not be obvious to people unfamiliar with JS, and just
want to use reveal to create slides.

**Comment by naholyr** [comment]
Note that `prez` allows you to include assets without modifying `index.html`: you can simply add a file named `includes.txt` containing this line (if you already had one, just append the line):

```
plugin/math/math.js
```

The plugin will be loaded in an old-school way (script src) but that does the job quite well, and no JS to type :)

**Comment by JoyMonteiro** [comment]
Oh, I was not aware... Thanks!
