### ISSUE TITLE
prez deploy

### ISSUE THREAD

**Issue by kurtisnelson** [lmtm/prez#8]
It'd be super handy to be able to have `prez deploy` copy dist/ over to the gh-pages branch, commit, and push.

**Comment by Delapouite** [comment]
Hi Kurt.

I'm afraid this feature is a bit out of the scope of what prez is meant to produce.

This kind of deploying task is quite general and should be handled by another dedicated tool or even a simple npm script.
For instance, gh-pages do not provide a websocket connection that some people may need to trigger the master / slave presentation mode.

Therefore, by focusing on core functionalities and remaining agnostic to the diffusion process, we can guarantee a better stability of the prez in the long term.

**Comment by Delapouite** [comment]
This is pretty much covered by this independent package : https://www.npmjs.com/package/gh-pages-deploy
